image: atlassian/default-image:2

infoStep: &infoStep
  - step:
      name: Info
      script:
        - node --version
        - npm --version
prepareStep: &prepareStep
  - step:
      name: Prepare
      script:
        - npm install
        - aws --version
      artifacts:
        - node_modules/**
sonarStep: &sonarStep
  - step:
      name: Sonar Scanner
      pipe: sonarsource/sonar-scanner-cli:latest
        script:
          - sonar-scanner -v

securityStep: &securityStep
  - step:
      name: Security
      script:
        - npm audit
        - npm run test

buildStep: &buildStep
  - step:
      name: Build
      script:
        - npm run build
      artifacts:
        - dist/**
        - build/**

deployS3AwsScript: &deployS3AwsScript
  script:
    - pipe: atlassian/aws-sam-deploy:0.3.2
      variables:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        AWS_DEFAULT_REGION: $AWS_REGION
        S3_BUCKET: $AWS_BUCKET_NAME
        STACK_NAME: stack"_"$APPLICATION_ENVIRONMENT"_"$(date +%Y%m%d_%H%M%S)"_"$BITBUCKET_BUILD_NUMBER
        SAM_TEMPLATE: 'template.yml'
        CAPABILITIES: ['CAPABILITY_IAM', 'CAPABILITY_AUTO_EXPAND']
        COMMAND: 'deploy-only'
pipelines:    
  branches:
    develop:
      - <<: *infoStep
      - <<: *prepareStep
      - <<: *sonarStep
      - <<: *securityStep
      #- <<: *buildStep
    test:
      - <<: *infoStep
      - <<: *prepareStep
      - <<: *securityStep
      #- <<: *buildStep
      - step:
          name: Deploy to test
          trigger: manual
          deployment: test
          <<: *deployS3AwsScript
    master:
      - <<: *infoStep
      - <<: *prepareStep
      - <<: *securityStep
      #- <<: *buildStep
      - step:
          name: Deploy to production
          trigger: manual
          deployment: production
          <<: *deployS3AwsScript
 